sudo: true
language: java
dist: trusty
group: edge
addons:
  apt:
    packages:
      - oracle-java9-installer
jdk: 
 - oraclejdk8
 - oraclejdk9
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
env:
  global:
  - DISPLAY=:99.0
  matrix:
  - PROJECT=greetings-gradle/2.12.0
  - PROJECT=greetings-maven/2.12.0
  - PROJECT=greetings-maven/2.13.0
  - PROJECT=domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng
before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10
script:
  - ls -al ~
  - cd $PROJECT
  - set -e
  - |
    if [ -f "pom.xml" ]; then
      mvn clean install
    fi
  - |
    if [ -f "gradlew" ]; then
      ./gradlew clean build
    fi
  -
  
