sudo: true
language: java
dist: trusty
group: edge
jdk: 
 - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
env:
  - PROJECT=greetings-gradle/2.12.0
  - PROJECT=greetings-maven/2.12.0
before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10
script:
  - cd $PROJECT
  - |
    if [ -f "pom.xml" ]; then
      mvn clean install
    fi
  - |
    if [ -f "gradlew" ]; then
      ./gradlew build
    fi
  